---
title: "EDS 223: Week 5"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
# Load Packages
library(sf) # vector handling
library(terra) # raster handling
library(tidyverse)
library(tmap) # map making
library(spData) # spatial data
library(spDataLarge) # spatial data
library(viridisLite)
library(units)
```

```{r}
# Read in data
# load raster dataset
elevation <- rast(system.file("raster/srtm.tif", package = "spDataLarge"))

# load vector dataset
boundary <- read_sf(system.file("vector/zion.gpkg", package = "spDataLarge"))
```

```{r}
# Check if coordinate reference systems match
if(crs(elevation) == crs(boundary)) {
  print("Coordinate reference systems match!")
} else {
  warning("Updating coordinate reference systems to match")
  boundary <- st_transform(boundary, st_crs(elevation))
}

# Verify
crs(elevation) == crs(boundary)
```

```{r}
# map
tm_shape(elevation) +
  tm_raster(title = "Elevation (m)") +
tm_shape(boundary) +
  tm_borders(lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
# crop raster to the extent of the vector object
elevation_cropped <- terra::crop(elevation, boundary)

# removes outside grid cells 
tm_shape(elevation_cropped) +
  tm_raster(title = "Elevation (m)") +
tm_shape(boundary) +
  tm_borders(lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
# mask the raster based on the vector object
# convert the cells outside the park to NA
elevation_masked <- terra::mask(elevation_cropped, boundary)

tm_shape(elevation_masked) +
  tm_raster(title = "Elevation (m)") +
tm_shape(boundary) +
  tm_borders(lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
# inverse mask
elevation_inverse_mask <- terra::mask(elevation_cropped, boundary, inverse = TRUE)

tm_shape(elevation_inverse_mask) +
  tm_raster(title = "Elevation (m)") +
tm_shape(boundary) +
  tm_borders(lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
# masking to cells inside of park
elevation_inside <- terra::mask(elevation_cropped, boundary)

# masking based on value of cells
elevation_mask <- elevation_inside

elevation_mask[elevation_mask < 2000] <- NA

tm_shape(elevation_mask) +
  tm_raster(title = "Elevation (m)") +
  tm_layout(legend.outside = TRUE)

# vectorized raster
elevation_mask_poly <- terra::as.polygons(elevation_mask) %>%
  st_as_sf()

tm_shape(elevation_mask_poly) +
  tm_polygons() +
  tm_layout(legend.outside = TRUE)
```

```{r}
data("zion_points", package = "spDataLarge")

crs(zion_points) == crs(elevation)

zion_points <- st_transform(zion_points, crs = st_crs(elevation))

tm_shape(elevation) +
  tm_raster() +
tm_shape(boundary) +
  tm_borders () +
tm_shape(zion_points) +
  tm_symbols() +
  tm_layout(legend.outside = TRUE)

pts_elevation <- terra::extract(elevation, zion_points)
  
zion_points <- cbind(zion_points, pts_elevation)
```

```{r}
zion_transect <- cbind(c(-133.2, -112.9),
                       c(37.45, 37.2)) %>%
  st_linestring() %>%
  st_sfc(crs = crs(elevation)) %>%
  st_sf(geometry = .)

tm_shape(elevation) +
  tm_raster() +
tm_shape(zion_transect) +
  tm_symbols()

zion_transect$id = 1:nrow(zion_transect)
zion_transect <- st_segmentize(zion_transect, dfMaxLength = 250)
zion_transect <- st_cast(zion_transect, "POINT")

zion_transect <- zion_transect %>%
  group_by(id) %>%
  mutate(dist = st_distance(geometry)[,1])

transect <- terra::extract(elevation, zion_transect)
zion_transect <- cbind(zion_transect, transect)

zion_transect <- zion_transect %>%
  filter(!is.na(elevation))

ggplot(zion_transect, aes(x = ID, y = elevation)) +
  geom_point()
                          
```

